### ISSUE TITLE
ALL CODE ARE BROKE

### ISSUE THREAD

**Issue by Samir-OP** [HELLMAKER0001/Alt-Detector#6]
ALL CODE ARE BROKE

**Comment by ItzSudhan** [comment]
What do you even mean by *All code are broke*

**Comment by TheFinality** [comment]
are u even real dynamo yt

**Comment by Sahil1337** [comment]
He dmed me don't worry !

**Comment by Samir-OP** [comment]
No

**Comment by DynamoYT** [comment]
ALL CODE ARE BROKEN

**Comment by DynamoYT** [comment]
I haven't used them 
https://media.tenor.com/images/4a657f6046b3cbaa235f73e927075792/tenor.gif

**Comment by ItzSudhan** [comment]
Uhh okay?

**Comment by HELLMAKER0001** [comment]
Dynamo dont write anything if u have problem then sa

**Comment by ItzSudhan** [comment]
Uhh just close this
